/* This header file machine-generated by mktyplib.exe */
/* Interface to type library: DSOFramer */

#ifndef _DSOFramer_H_
#define _DSOFramer_H_

DEFINE_GUID(LIBID_DSOFramer,0x00460180L,0x9E5E,0x11D5,0xB7,0xC8,0xB8,0x26,0x90,0x41,0xDD,0x57);
#ifndef BEGIN_INTERFACE
#define BEGIN_INTERFACE
#endif

typedef enum dsoBorderStyle {
    dsoBorderNone = 0,
    dsoBorderFlat,
    dsoBorder3D,
    dsoBorder3DThin
} dsoBorderStyle;

typedef enum dsoShowDialogType {
    dsoDialogNew = 0,
    dsoDialogOpen,
    dsoDialogSave,
    dsoDialogSaveCopy,
    dsoDialogPrint,
    dsoDialogPageSetup,
    dsoDialogProperties
} dsoShowDialogType;

typedef enum dsoFileCommandType {
    dsoFileNew = 0,
    dsoFileOpen,
    dsoFileClose,
    dsoFileSave,
    dsoFileSaveAs,
    dsoFilePrint,
    dsoFilePageSetup,
    dsoFileProperties,
    dsoFilePrintPreview
} dsoFileCommandType;

DEFINE_GUID(IID__FramerControl,0x00460181L,0x9E5E,0x11D5,0xB7,0xC8,0xB8,0x26,0x90,0x41,0xDD,0x57);

/* Definition of interface: _FramerControl */
#undef INTERFACE
#define INTERFACE _FramerControl

DECLARE_INTERFACE_(_FramerControl, IDispatch)
{
BEGIN_INTERFACE
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* _FramerControl methods */
    STDMETHOD(Activate)(THIS) PURE;
    STDMETHOD(get_ActiveDocument)(THIS_ IDispatch * FAR* ppdisp) PURE;
    STDMETHOD(CreateNew)(THIS_ BSTR ProgIdOrTemplate) PURE;
    STDMETHOD(Open)(THIS_ VARIANT Document, VARIANT ReadOnly, VARIANT ProgId, VARIANT WebUsername, VARIANT WebPassword) PURE;
    STDMETHOD(Save)(THIS_ VARIANT SaveAsDocument, VARIANT OverwriteExisting, VARIANT WebUsername, VARIANT WebPassword) PURE;
    STDMETHOD(_PrintOutOld)(THIS_ VARIANT PromptToSelectPrinter) PURE;
    STDMETHOD(Close)(THIS) PURE;
    STDMETHOD(put_Caption)(THIS_ BSTR bstr) PURE;
    STDMETHOD(get_Caption)(THIS_ BSTR FAR* pbstr) PURE;
    STDMETHOD(put_Titlebar)(THIS_ VARIANT_BOOL vbool) PURE;
    STDMETHOD(get_Titlebar)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(put_Toolbars)(THIS_ VARIANT_BOOL vbool) PURE;
    STDMETHOD(get_Toolbars)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(put_ModalState)(THIS_ VARIANT_BOOL vbool) PURE;
    STDMETHOD(get_ModalState)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(ShowDialog)(THIS_ dsoShowDialogType DlgType) PURE;
    STDMETHOD(put_EnableFileCommand)(THIS_ dsoFileCommandType Item, VARIANT_BOOL vbool) PURE;
    STDMETHOD(get_EnableFileCommand)(THIS_ dsoFileCommandType Item, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(put_BorderStyle)(THIS_ dsoBorderStyle style) PURE;
    STDMETHOD(get_BorderStyle)(THIS_ dsoBorderStyle FAR* pstyle) PURE;
    STDMETHOD(put_BorderColor)(THIS_ OLE_COLOR clr) PURE;
    STDMETHOD(get_BorderColor)(THIS_ OLE_COLOR FAR* pclr) PURE;
    STDMETHOD(put_BackColor)(THIS_ OLE_COLOR clr) PURE;
    STDMETHOD(get_BackColor)(THIS_ OLE_COLOR FAR* pclr) PURE;
    STDMETHOD(put_ForeColor)(THIS_ OLE_COLOR clr) PURE;
    STDMETHOD(get_ForeColor)(THIS_ OLE_COLOR FAR* pclr) PURE;
    STDMETHOD(put_TitlebarColor)(THIS_ OLE_COLOR clr) PURE;
    STDMETHOD(get_TitlebarColor)(THIS_ OLE_COLOR FAR* pclr) PURE;
    STDMETHOD(put_TitlebarTextColor)(THIS_ OLE_COLOR clr) PURE;
    STDMETHOD(get_TitlebarTextColor)(THIS_ OLE_COLOR FAR* pclr) PURE;
    STDMETHOD(ExecOleCommand)(THIS_ long OLECMDID, VARIANT Options, VARIANT FAR* vInParam, VARIANT FAR* vInOutParam) PURE;
    STDMETHOD(put_Menubar)(THIS_ VARIANT_BOOL vbool) PURE;
    STDMETHOD(get_Menubar)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(put_HostName)(THIS_ BSTR bstr) PURE;
    STDMETHOD(get_HostName)(THIS_ BSTR FAR* pbstr) PURE;
    STDMETHOD(get_DocumentFullName)(THIS_ BSTR FAR* pbstr) PURE;
    STDMETHOD(PrintOut)(THIS_ VARIANT PromptUser, VARIANT PrinterName, VARIANT Copies, VARIANT FromPage, VARIANT ToPage, VARIANT OutputFile) PURE;
    STDMETHOD(PrintPreview)(THIS) PURE;
    STDMETHOD(PrintPreviewExit)(THIS) PURE;
    STDMETHOD(get_IsReadOnly)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(get_IsDirty)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(HttpInit)(THIS_ VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(HttpAddPostString)(THIS_ BSTR strName, BSTR strValue, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(HttpPost)(THIS_ BSTR bstr, BSTR FAR* pRet) PURE;
    STDMETHOD(SetTrackRevisions)(THIS_ long vbool, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(SetCurrUserName)(THIS_ BSTR strCurrUserName, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(HttpAddPostCurrFile)(THIS_ BSTR strFileID, BSTR strFileName, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(SetCurrTime)(THIS_ BSTR strValue, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(get_GetApplication)(THIS_ IDispatch * FAR* ppdisp) PURE;
    STDMETHOD(SetFieldValue)(THIS_ BSTR strFieldName, BSTR strValue, BSTR strCmdOrSheetName, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(GetFieldValue)(THIS_ BSTR strFieldName, BSTR strCmdOrSheetName, BSTR FAR* strValue) PURE;
    STDMETHOD(SetMenuDisplay)(THIS_ long lMenuFlag, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(ProtectDoc)(THIS_ long lProOrUn, long lProType, BSTR strProPWD, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(ShowRevisions)(THIS_ long nNewValue, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(InSertFile)(THIS_ BSTR strFieldPath, long lPos, VARIANT_BOOL FAR* pbool) PURE;
    STDMETHOD(LoadOriginalFile)(THIS_ VARIANT strFieldPath, VARIANT strFileType, long FAR* pbool) PURE;
    STDMETHOD(SaveAs)(THIS_ VARIANT strFileName, VARIANT dwFileFormat, long FAR* pbool) PURE;
    STDMETHOD(DeleteLocalFile)(THIS_ BSTR strFilePath) PURE;
    STDMETHOD(GetTempFilePath)(THIS_ BSTR FAR* strValue) PURE;
    STDMETHOD(ShowView)(THIS_ long dwViewType, long FAR* pbool) PURE;
    STDMETHOD(FtpConnect)(THIS_ BSTR strURL, long lPort, BSTR strUser, BSTR strPwd, long FAR* pbool) PURE;
    STDMETHOD(FtpGetFile)(THIS_ BSTR strRemoteFile, BSTR strLocalFile, long FAR* pbool) PURE;
    STDMETHOD(FtpPutFile)(THIS_ BSTR strLocalFile, BSTR strRemoteFile, long blOverWrite, long FAR* pbool) PURE;
    STDMETHOD(FtpDisConnect)(THIS_ long FAR* pbool) PURE;
    STDMETHOD(DownloadFile)(THIS_ BSTR strRemoteFile, BSTR strLocalFile, BSTR FAR* strValue) PURE;
    STDMETHOD(HttpAddPostFile)(THIS_ BSTR strFileID, BSTR strFileName, long FAR* pbool) PURE;
    STDMETHOD(GetRevCount)(THIS_ long FAR* pbool) PURE;
    STDMETHOD(GetRevInfo)(THIS_ long lIndex, long lType, BSTR FAR* pbool) PURE;
    STDMETHOD(SetValue)(THIS_ BSTR strValue, BSTR strName, long FAR* pbool) PURE;
    STDMETHOD(SetDocVariable)(THIS_ BSTR strVarName, BSTR strValue, long lOpt, long FAR* pbool) PURE;
    STDMETHOD(SetPageAs)(THIS_ BSTR strLocalFile, long lPageNum, long lType, long FAR* pbool) PURE;
    STDMETHOD(ReplaceText)(THIS_ BSTR strSearchText, BSTR strReplaceText, long lGradation, long FAR* pbool) PURE;
    STDMETHOD(GetEnvironmentVariable)(THIS_ BSTR EnvironmentName, BSTR FAR* strValue) PURE;
    STDMETHOD(GetOfficeVersion)(THIS_ BSTR strName, BSTR FAR* strValue) PURE;
};

DEFINE_GUID(DIID__DFramerCtlEvents,0x00460185L,0x9E5E,0x11D5,0xB7,0xC8,0xB8,0x26,0x90,0x41,0xDD,0x57);

/* Definition of dispatch interface: _DFramerCtlEvents */
#undef INTERFACE
#define INTERFACE _DFramerCtlEvents

DECLARE_INTERFACE_(_DFramerCtlEvents, IDispatch)
{
BEGIN_INTERFACE
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* _DFramerCtlEvents methods:
    HRESULT OnFileCommand(dsoFileCommandType Item, VARIANT_BOOL FAR* Cancel);
    HRESULT OnDocumentOpened(BSTR File, IDispatch * Document);
    HRESULT OnDocumentClosed(void);
    HRESULT OnActivationChange(VARIANT_BOOL fGoingActive);
    HRESULT BeforeDocumentClosed(IDispatch * Document, VARIANT_BOOL FAR* Cancel);
    HRESULT BeforeDocumentSaved(IDispatch * Document, BSTR Location, VARIANT_BOOL FAR* Cancel);
    HRESULT OnPrintPreviewExit(void);
    HRESULT NotifyCtrlReady(void);
    */
};

DEFINE_GUID(CLSID_FramerControl,0x00460182L,0x9E5E,0x11D5,0xB7,0xC8,0xB8,0x26,0x90,0x41,0xDD,0x57);

#ifdef __cplusplus
class FramerControl;
#endif

#endif
